### ISSUE TITLE
incorrect constant for two-photon decay rate

### ISSUE THREAD

**Issue by lukashergt** [nanoomlee/HYREC-2#1]
Line 55 of `hydrogen.h`:
```h
#define L2s1s     8.2206               /* 2s -> 1s two-photon decay rate in s^{-1} (Labzowsky et al 2005) */
```
I'm pretty sure that there must be a 9 missing in that number, i.e. it should be `8.22906` instead of `8.2206`, which must be a typo in the Labzowsky et al (2005) paper. 

Compare for example with the following references:
* [Amaro et al (2011)](https://iopscience.iop.org/article/10.1088/1751-8113/44/24/245302)
* [Filippin et al (2016)](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.93.012517)
* [Sommerfeldt et al (2020)](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.102.042811)

**Comment by nanoomlee** [comment]
Thank you for pointing this out! I will check this more carefully but I've checked that this possible difference in two-photon decay rate doesn't affect the accuracy of the code.
